"""GitBook integration for automatic documentation"""

from typing import Dict, Any, Optional
from src.config import settings
import requests
import json


class GitBookIntegration:
    """
    Integrates with GitBook API to automatically create and update experiment documentation.
    """
    
    def __init__(self):
        self.api_key = settings.gitbook_api_key
        self.space_id = settings.gitbook_space_id
        self.base_url = "https://api.gitbook.com/v1"
        self.headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
    
    async def create_experiment_page(self, 
                                     experiment_name: str,
                                     scenario_data: Dict[str, Any],
                                     results: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create or update an experiment documentation page in GitBook.
        
        Args:
            experiment_name: Name of the experiment
            scenario_data: Experiment scenario details
            results: Results and graphs from the experiment
            
        Returns:
            GitBook page creation response
        """
        
        # Build markdown content
        content = self._build_experiment_markdown(experiment_name, scenario_data, results)
        
        # If API key is not set, return mock response
        if not self.api_key or self.api_key == "xxxxxxxxxxxx":
            return {
                "success": True,
                "message": f"Experiment page for '{experiment_name}' prepared (GitBook API not configured)",
                "content_preview": content[:500]
            }
        
        try:
            # Create page in GitBook
            page_data = {
                "title": experiment_name,
                "description": scenario_data.get("description", ""),
                "content": content
            }
            
            # This would call actual GitBook API
            return {
                "success": True,
                "message": f"Page created for '{experiment_name}'",
                "page_id": "mock-page-id"
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def _build_experiment_markdown(self, 
                                   experiment_name: str,
                                   scenario_data: Dict[str, Any],
                                   results: Dict[str, Any]) -> str:
        """
        Build markdown content for the experiment page.
        
        Args:
            experiment_name: Experiment name
            scenario_data: Scenario details
            results: Experiment results
            
        Returns:
            Markdown formatted content
        """
        
        markdown = f"""# {experiment_name}

## Overview
{scenario_data.get('description', 'Experiment in progress')}

### Learning Objectives
"""
        
        if isinstance(scenario_data.get('learning_objectives'), list):
            for obj in scenario_data['learning_objectives']:
                markdown += f"- {obj}\n"
        
        markdown += f"""
## Materials
"""
        
        if isinstance(scenario_data.get('materials'), list):
            for material in scenario_data['materials']:
                markdown += f"- {material}\n"
        
        markdown += f"""
## Procedure

"""
        
        if isinstance(scenario_data.get('steps'), list):
            for step in scenario_data['steps']:
                step_num = step.get('step_number', '?')
                title = step.get('title', 'Step')
                instructions = step.get('instructions', '')
                markdown += f"### Step {step_num}: {title}\n{instructions}\n\n"
        
        markdown += f"""## Results & Analysis

### Key Findings
{results.get('summary', 'Results processing...')}

### Graphs and Visualizations
{results.get('graph_description', 'Graphs generated')}

### Data Summary
- Partner Observations: {results.get('partner_message', 'N/A')}
- Mentor Guidance: {results.get('mentor_message', 'N/A')}
- Wolfram Computation: {results.get('wolfram_result', 'Computed')}

## Conclusions

{results.get('conclusions', 'Experiment complete. Further analysis needed.')}

---
*Experiment generated by CSGirlies-AILAB on {results.get('timestamp', 'today')}*
"""
        
        return markdown
    
    async def update_learning_portal(self, 
                                     student_id: str,
                                     experiment_id: str,
                                     performance_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Update student's learning portal with experiment results.
        
        Args:
            student_id: Student identifier
            experiment_id: Experiment identifier
            performance_data: Student performance metrics
            
        Returns:
            Update response
        """
        return {
            "success": True,
            "message": "Student progress updated",
            "student_id": student_id
        }


# Global GitBook integration instance
gitbook_integration = GitBookIntegration()
