"""Export utilities for lab reports - PDF, Markdown, CSV"""

from pathlib import Path
from typing import Dict, Any, List
import json
from datetime import datetime


class ReportExporter:
    """
    Export lab reports in multiple formats.

    Supports:
    - Markdown (default, already implemented)
    - PDF (via markdown → HTML → PDF)
    - CSV (for data analysis)
    - JSON (for API integration)
    """

    def __init__(self):
        self.exports_dir = Path("lab_reports/exports")
        self.exports_dir.mkdir(parents=True, exist_ok=True)

    def export_to_markdown(self, report_content: str, filename: str) -> str:
        """
        Export report to Markdown file.

        Args:
            report_content: Markdown content
            filename: Output filename

        Returns:
            Path to exported file
        """
        filepath = self.exports_dir / f"{filename}.md"
        filepath.write_text(report_content, encoding='utf-8')
        return str(filepath)

    def export_to_html(self, markdown_content: str, filename: str) -> str:
        """
        Convert Markdown to HTML for PDF generation.

        Args:
            markdown_content: Markdown content
            filename: Output filename

        Returns:
            Path to HTML file
        """
        try:
            import markdown
            html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Lab Report - CSGirlies-AILAB</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{
            color: #667eea;
            border-bottom: 3px solid #667eea;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #764ba2;
            margin-top: 30px;
        }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
        }}
        pre {{
            background: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }}
        blockquote {{
            border-left: 4px solid #667eea;
            padding-left: 20px;
            margin-left: 0;
            color: #555;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }}
        th {{
            background: #667eea;
            color: white;
        }}
        .footer {{
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #999;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
{markdown.markdown(markdown_content, extensions=['tables', 'fenced_code', 'codehilite'])}
<div class="footer">
    <p>Generated by CSGirlies-AILAB | CS Girlies Hackathon 2024</p>
    <p>Exported on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
</div>
</body>
</html>
"""
            filepath = self.exports_dir / f"{filename}.html"
            filepath.write_text(html_content, encoding='utf-8')
            return str(filepath)
        except ImportError:
            # Fallback if markdown not installed
            return None

    def export_to_pdf(self, markdown_content: str, filename: str) -> str:
        """
        Export report to PDF.

        Requires: wkhtmltopdf or weasyprint

        Args:
            markdown_content: Markdown content
            filename: Output filename

        Returns:
            Path to PDF file or None if failed
        """
        html_file = self.export_to_html(markdown_content, filename)
        if not html_file:
            return None

        pdf_path = self.exports_dir / f"{filename}.pdf"

        # Try weasyprint first (pure Python)
        try:
            from weasyprint import HTML
            HTML(html_file).write_pdf(str(pdf_path))
            return str(pdf_path)
        except ImportError:
            pass

        # Try pdfkit (requires wkhtmltopdf)
        try:
            import pdfkit
            pdfkit.from_file(html_file, str(pdf_path))
            return str(pdf_path)
        except (ImportError, OSError):
            pass

        # Fallback: return HTML file if PDF conversion fails
        return html_file

    def export_to_csv(self, conversation_data: List[Dict[str, Any]],
                      observations: Dict[str, Any],
                      filename: str) -> str:
        """
        Export experiment data to CSV for analysis.

        Args:
            conversation_data: List of messages
            observations: Student observations
            filename: Output filename

        Returns:
            Path to CSV file
        """
        import csv

        filepath = self.exports_dir / f"{filename}.csv"

        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)

            # Header
            writer.writerow(['Type', 'Speaker', 'Content', 'Timestamp'])

            # Conversation data
            for msg in conversation_data:
                writer.writerow([
                    msg.get('role', 'unknown'),
                    msg.get('sender', ''),
                    msg.get('content', ''),
                    datetime.now().isoformat()
                ])

            # Observations
            writer.writerow([])
            writer.writerow(['Observations', '', '', ''])
            for key, value in observations.items():
                writer.writerow(['observation', key, value, ''])

        return str(filepath)

    def export_to_json(self, full_report_data: Dict[str, Any], filename: str) -> str:
        """
        Export complete report as JSON.

        Args:
            full_report_data: Complete report data
            filename: Output filename

        Returns:
            Path to JSON file
        """
        filepath = self.exports_dir / f"{filename}.json"

        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(full_report_data, f, indent=2, ensure_ascii=False)

        return str(filepath)

    def export_all_formats(self,
                          markdown_content: str,
                          conversation_data: List[Dict[str, Any]],
                          observations: Dict[str, Any],
                          full_data: Dict[str, Any],
                          base_filename: str) -> Dict[str, str]:
        """
        Export report in all available formats.

        Args:
            markdown_content: Markdown report
            conversation_data: Conversation messages
            observations: Student observations
            full_data: Complete report data
            base_filename: Base name for files

        Returns:
            Dict with paths to all exported files
        """
        exports = {}

        # Markdown
        exports['markdown'] = self.export_to_markdown(markdown_content, base_filename)

        # HTML
        html_path = self.export_to_html(markdown_content, base_filename)
        if html_path:
            exports['html'] = html_path

        # PDF (if possible)
        pdf_path = self.export_to_pdf(markdown_content, base_filename)
        if pdf_path:
            exports['pdf'] = pdf_path

        # CSV
        exports['csv'] = self.export_to_csv(conversation_data, observations, base_filename)

        # JSON
        exports['json'] = self.export_to_json(full_data, base_filename)

        return exports


# Quick utility functions
def quick_export_markdown(content: str, filename: str) -> str:
    """Quick markdown export"""
    exporter = ReportExporter()
    return exporter.export_to_markdown(content, filename)


def quick_export_pdf(markdown_content: str, filename: str) -> str:
    """Quick PDF export"""
    exporter = ReportExporter()
    return exporter.export_to_pdf(markdown_content, filename)


def quick_export_all(markdown_content: str,
                     conversation: List[Dict],
                     observations: Dict,
                     full_data: Dict,
                     filename: str) -> Dict[str, str]:
    """Quick export in all formats"""
    exporter = ReportExporter()
    return exporter.export_all_formats(
        markdown_content,
        conversation,
        observations,
        full_data,
        filename
    )
